version: "3"

services:
  frontend:
    container_name: frontend
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf 
    networks:
      - mynetwork
    depends_on: 
      - backend_service

  backend_service:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

